/**
 * BuildLight Type Definitions
 * These match the Prisma schema enums
 */

export enum Role {
  OWNER = "OWNER",
  PROJECT_MANAGER = "PROJECT_MANAGER",
  FIELD_WORKER = "FIELD_WORKER",
  SUBCONTRACTOR = "SUBCONTRACTOR",
  CLIENT = "CLIENT",
}

export enum Plan {
  STARTER = "STARTER",
  PRO = "PRO",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  TRIALING = "TRIALING",
  PAST_DUE = "PAST_DUE",
  CANCELED = "CANCELED",
  INCOMPLETE = "INCOMPLETE",
  INCOMPLETE_EXPIRED = "INCOMPLETE_EXPIRED",
  UNPAID = "UNPAID",
}

export enum ProjectStatus {
  PLANNING = "PLANNING",
  IN_PROGRESS = "IN_PROGRESS",
  ON_HOLD = "ON_HOLD",
  COMPLETED = "COMPLETED",
  ARCHIVED = "ARCHIVED",
}

export enum Weather {
  SUNNY = "SUNNY",
  PARTLY_CLOUDY = "PARTLY_CLOUDY",
  CLOUDY = "CLOUDY",
  RAINY = "RAINY",
  SNOWY = "SNOWY",
  WINDY = "WINDY",
}

export enum TaskPhase {
  PLANNING = "PLANNING",
  DESIGN = "DESIGN",
  PERMITS = "PERMITS",
  FOUNDATION = "FOUNDATION",
  FRAMING = "FRAMING",
  ELECTRICAL = "ELECTRICAL",
  PLUMBING = "PLUMBING",
  HVAC = "HVAC",
  INSULATION = "INSULATION",
  DRYWALL = "DRYWALL",
  FINISHING = "FINISHING",
  LANDSCAPING = "LANDSCAPING",
  INSPECTION = "INSPECTION",
  CLOSEOUT = "CLOSEOUT",
}
